# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
#xcode_workspace: Example/GlyuckDataGrid.xcworkspace
#xcode_scheme: GlyuckDataGrid-Example
cache: cocoapods
podfile: Example/Podfile
osx_image: xcode10
before_install:
- |
  BUNDLE_GEMFILE=Example/Gemfile bundle install
  BUNDLE_GEMFILE=Example/Gemfile bundle exec pod repo update
  BUNDLE_GEMFILE=Example/Gemfile bundle exec pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- xcodebuild test -workspace Example/GlyuckDataGrid.xcworkspace -scheme GlyuckDataGrid-Example -sdk iphonesimulator12.1 -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.1' | xcpretty
